# Site settings
title: Aveek Saha
email: aveek.s98@gmail.com
url: https://aveek-saha.github.io
description: "Hi I'm Aveek Saha and this is my profile."
keywords: "aveek, saha, aveek saha"
skills: "Web | Mobile | Desktop app Developer"
meta_author: Aveek Saha

# Google webmaster tools
google_verify: googlec062211d23b61296.html

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: aveek-saha

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 282729 #80B3FF
  primary-rgb: "30, 30, 30" #"128,179,255"
  secondary: DA294F #FD6E8A
  secondary-dark: C42547 #A2122F

# Footer settings
footer:
  copyright: Aveek Saha
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/Aveek-Saha
  - title: linkedin
    url: https://www.linkedin.com/in/aveek-saha
  - title: blogger
    url: https://aveeksaha.gitlab.io/
  - title: behance
    url: https://www.behance.net/aveeks/
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100001098414449
  - title: instagram
    url: https://www.instagram.com/aveek68/

# Postal address (add as many lines as necessary)
address:
  - line: Bangalore , Karnataka , India

# Build settings
markdown: kramdown
permalink: pretty
